# Project: ERP
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Student.o Admin.o Teacher.o
LINKOBJ  = main.o Student.o Admin.o Teacher.o
LIBS     = -L"D:/Applications/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Applications/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Applications/Dev-Cpp/TDM-GCC-64/include" -I"D:/Applications/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Applications/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Applications/Dev-Cpp/TDM-GCC-64/include" -I"D:/Applications/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Applications/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Applications/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ERP.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Applications\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Student.o: Student.cpp
	$(CPP) -c Student.cpp -o Student.o $(CXXFLAGS)

Admin.o: Admin.cpp
	$(CPP) -c Admin.cpp -o Admin.o $(CXXFLAGS)

Teacher.o: Teacher.cpp
	$(CPP) -c Teacher.cpp -o Teacher.o $(CXXFLAGS)
